### ISSUE TITLE
Changelog missing

### ISSUE THREAD

**Issue by SimJoSt** [afterlogic/nextcloud-connector#10]
When performing the update of the plugin from version `` to version `` I was trying to locate the changelog to see what had changed, but couldn't find any.

There are not tags and releases:
+ https://github.com/afterlogic/nextcloud-connector/tags
+ https://github.com/afterlogic/nextcloud-connector/releases

No `CHANGELOG.md` in the root of the repo.  
And the `VERSION` file only contains a version number, but no additional information.

Did I overlook something?

**Comment by afterlogic-support** [comment]
We update the plugin to ensure its compatibility with current version of Nextcloud, there are no other changes in the connector package. If you might be looking for changelog of WebMail itself, it can be found at:
https://afterlogic.com/docs/webmail-lite-8/changelog

**Comment by afterlogic-support** [comment]
Although, I do agree that it would be useful to include the changelog and we'll consider doing so in the future releases.
