### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by tombom105** [afterlogic/nextcloud-connector#11]
Hello,
I am having an issue where only people in the admins group of Nextcloud can see the mail icon on the top bar to login to Afterlogic. 
Tried reinstalling, rebooting the server and a few other things but no luck.
Is this a known issue?

**Comment by afterlogic-support** [comment]
If you log in as admin, do you have "File path to AfterLogic WebMail installation" value specified under Settings > Additional settings > AfterLogic WebMail?

**Comment by afterlogic-support** [comment]
Looks like the issue occurs only when "File path to AfterLogic WebMail installation" is not specified in app settings. It, however, is a valid approach for those cases when WebMail and NextCloud are on different servers, see [Nextcloud integration](https://afterlogic.com/docs/webmail-pro-8/configuring-webmail/nextcloud-integration) documentation page.

If that's the case, you can correct the issue by editing `apps/afterlogic/appinfo/app.php` file, replace the following line:
```php
if (('' !== $sUrl && '' !== $sPath) || OC_User::isAdminUser(OC_User::getUser()))
```
with:
```php
if ('' !== $sUrl || OC_User::isAdminUser(OC_User::getUser()))
```

We'll have this modification added to the next update of the connector package.

**Comment by tombom105** [comment]
This worked perfectly!
Thank you so much for the quick response.
I appreciate the excellent product you all have made.
Have a great day!
