### ISSUE TITLE
App doesn't start after updating to 1.2.19 on Nextcloud 18.0.7

### ISSUE THREAD

**Issue by SeAIMe** [afterlogic/nextcloud-connector#13]
Hi there,

I'm on Nextcloud 18.0.7 stable and just updated the Afterlogic Nextcloud-Connector to 1.2.19.

Now the Afterlogic app won't start anymore. There's nothing in the Nextcloud logs.

Accessing my Afterlogic installation directly with the browser works, so it seems it's an issue with the connector app only.

Thanks for any help!

SeAlMe

**Comment by afterlogic-support** [comment]
Are you getting a blank white screen when switching to Afterlogic tab?

And do you have Afterlogic WebMail section under Admin and Personal settings? If yes, does it work if you save those settings - or do you get errors there?

**Comment by SeAIMe** [comment]
Yes, I'm getting just a blank white screen!

I hit the 'Save' button for Admin and Personal settings without getting any errors. It shows 'saved successfully'.

But I realized that my WebMail installation is still on 8.3.16! Maybe that's causing the issue?

I'll do an update and report back afterwards.

**Comment by afterlogic-support** [comment]
That version should work just fine, actually. I have a couple of suggestions what could go wrong:
1) is there any chance that webmail and nextcloud are installed on different servers, or at least have a different host/IP in their access URLs?
If yes, try editing `apps/afterlogic/lib/Controller/PageController.php` file:
```php
                $csp->addAllowedFrameDomain("'self'");
```

Replace that line with something like
```php
                $csp->addAllowedFrameDomain("webmail.yourdomain.com");
```
where `webmail.yourdomain.com` is a hostname of WebMail installation you use.

2) also, can you try supplying an empty value for "File path to Afterlogic WebMail installation:" and see if WebMail opens then?

**Comment by SeAIMe** [comment]
Both installations are on the same server/host with different subdomains.

Nextcloud: cloud.mydomain.de
Aferlogic: webmail.mydomain.de

Nevertheless I tried your suggestions but I still get the blank white screen.

**Comment by afterlogic-support** [comment]
OK so we might be heading in the right direction, then.
Please try replacing `apps/afterlogic/lib/Controller/PageController.php` with one in the attached archive:
[PageController.zip](https://github.com/afterlogic/nextcloud-connector/files/5027320/PageController.zip)
and let us know if it works for you.
Thanks.

**Comment by SeAIMe** [comment]
It works!

Thanks a lot for your prompt help. Highly appreciated!

**Comment by afterlogic-support** [comment]
Glad to help! Will have the package updated with this modification later today.

**Comment by zecman** [comment]
Maybe you also need to extend 'script-src'?

**Comment by afterlogic-support** [comment]
Not entirely sure what for; connector doesn't include any scripts off webmail location, it only places WebMail into Iframe.

**Comment by zecman** [comment]
Right, adding this policy did not help here. It still does not load with the PageController.php from the archive above. I Will wait until you release the updated package. Thanks.

**Comment by eldelacajita** [comment]
Hi! I'm having a similar issue. Using Afterlogic 1.2.20 on Nextcloud 18.0.6.
Is this fix already released?

**Comment by afterlogic-support** [comment]
The fix is indeed included in the latest package - `apps/afterlogic/lib/Controller/PageController.php` file, line 60::
```php
$sUrlParts = parse_url($sUrl);
$csp->addAllowedFrameDomain($sUrlParts["host"]);
$oTemplate->setContentSecurityPolicy($csp);
```
If this doesn't work for you for some reason, you can try replacing $sUrlParts["host"] with an actual domain where you have WebMail installation running. 
BTW, is my understanding correct that you have Nextcloud and WebMail installations on different domains?

**Comment by eldelacajita** [comment]
Thank you for you reply!

>  BTW, is my understanding correct that you have Nextcloud and WebMail installations on different domains?

That is correct. I will try your suggestion.

**Comment by afterlogic-support** [comment]
Please also note that, if you set empty value for "File path to Afterlogic WebMail installation", you need to enable POST login by setting **AllowPostLogin** to **true** in  `data/settings/modules/Core.config.json` configuration file:
https://afterlogic.com/docs/webmail-lite-8/configuring-webmail/nextcloud-integration
Without that, attempt of logging onto remote server may result in a white screen indeed.

**Comment by eldelacajita** [comment]
That did it, thanks!
