### ISSUE TITLE
Cannot acces settings if user is group admin.

### ISSUE THREAD

**Issue by solkmaaker** [afterlogic/nextcloud-connector#14]
Behavior is similar to this rainloop issue: [https://help.nextcloud.com/t/user-cannot-access-the-settings-menu/70972](https://help.nextcloud.com/t/user-cannot-access-the-settings-menu/70972)
Regular user can access it's settings, and set user and pass for afterlogic webmail.
Admin user cannot access hes settings at all, nextcloud redirects to default app (files).

Nextcloud log does not say anything.

edit: afterlogic webmail is not on same server as nextcloud (if that helps)

**Comment by afterlogic-support** [comment]
What version of Nextcloud and Afterlogic connector are you running?

**Comment by solkmaaker** [comment]
Oh, yes, sorry i forgot.
Both are latest:
Afterlogic Aurora Corporate  8.5.0
Nextcloud 19.0.3

**Comment by afterlogic-support** [comment]
And the connector version is the latest 1.2.19 too?

**Comment by solkmaaker** [comment]
Yes, connector version is 1.12.19

**Comment by afterlogic-support** [comment]
I think we've located the reason of the issue. In your Nextcloud installation, try editing `apps/afterlogic/appinfo/app.php` file, modify the line:
```php
\OCP\App::registerAdmin('afterlogic', 'lib/admin');
```

as follows:

```php
if (\OC_User::isAdminUser(\OC_User::getUser()))
    \OCP\App::registerAdmin('afterlogic', 'lib/admin');
```

Does it help?

**Comment by solkmaaker** [comment]
Yes.

Now it works OK, group admin can enter credentials in settings screen, and gets logged in automatically to afterlogic webmail.

Thank you.

**Comment by afterlogic-support** [comment]
Have just uploaded an updated app to Nextcloud appstore, the code on Github updated as well. Thanks.
