### ISSUE TITLE
Update for Nextcloud 20

### ISSUE THREAD

**Issue by SeAIMe** [afterlogic/nextcloud-connector#15]
Hi there,

As Nextcloud is rolling out the 20 stable release, any plans when Afterlogic will follow?

Thanks!

**Comment by afterlogic-support** [comment]
Yes, we will definitely look into that, and if that requires adjusting the connector (aside from changing supported version numbers) we'll see what we can do.

**Comment by SeAIMe** [comment]
That sounds good!

Thank you for your instant support!

**Comment by afterlogic-support** [comment]
Our test shows that the connector works on Nextcloud 20 just fine. We will publish the updated version shortly. Meantime, it should be safe to skip version-related warning when installing the connector from marketplace.

**Comment by afterlogic-support** [comment]
We have just released an updated version of Afterlogic connector for Nextcloud, you can download and install it from Nextcloud 20.
