### ISSUE TITLE
Future request: Send attached files using nextcloud

### ISSUE THREAD

**Issue by mastir** [afterlogic/nextcloud-connector#16]
Some of mail servers do not accept big attachments. Is it possible to upload attached files into nextcloud and send links? This future implemented in roundcube plugin for nextcloud. Files inserted as preview image with link before signature. This is very useful, most of users do not understand difference in sending email with 2gb attachment and email with link to file in nextcloud.

**Comment by afterlogic-support** [comment]
Currently, we only offer basic integration of WebMail with Nextcloud, limited to single sign-on. In future, we do consider implementing deeper integration, including the use of Nextcloud file storage. Thank you.
