### ISSUE TITLE
What prediction of attaching files using nextcloud?

### ISSUE THREAD

**Issue by Katrovisch** [afterlogic/nextcloud-connector#18]
This feature is very useful which has available in the other native webmail of nextcloud

**Comment by afterlogic-support** [comment]
We don't have this feature in the product roadmap at the moment. Please feel free to request a feature at:

https://afterlogic.uservoice.com/forums/932335-webmail-pro

We use that resource when developing product's roadmap, so if the feature gets a good number of votes, there's a better chance of it getting implemented.
