### ISSUE TITLE
Not compatible with Nextcloud 25?

### ISSUE THREAD

**Issue by nextgen-networks** [afterlogic/nextcloud-connector#19]
Connector cannot be activated in Nextcloud 25
Will get deactivated within update procedure from Nextcloud 24.x.x to 25

**Comment by afterlogic-support** [comment]
Sure, will look into it.

**Comment by afterlogic-support** [comment]
We've just released version 2.0.5 compatible with Nextcloud v25. GitHub repository is updated as well.
