### ISSUE TITLE
deprecated /appinfo/app.php

### ISSUE THREAD

**Issue by supercoil** [afterlogic/nextcloud-connector#23]
Nextcloud log is flooded with the following message:
`[afterlogic] Debug: /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.`
I'm on Nextcloud 27 with the latest connector

**Comment by afterlogic-support** [comment]
Will have this looked into. In the meantime, I'd recommend to edit `config/config.php` file of Nextcloud and set:
```php
"loglevel" => 3,
```
That way, only actual errors are logged, non-critical warnings are not.

**Comment by supercoil** [comment]
OK, thanks for the tip

**Comment by afterlogic-support** [comment]
This has been corrected, we've released version 2.0.8 of the connector, repository is updated as well. Thanks!
