### ISSUE TITLE
FIrefox/Chrome can't open this page

### ISSUE THREAD

**Issue by vianmora** [afterlogic/nextcloud-connector#26]
I've installd afterlogic in my server, and it works on my mail url 
and now, i would like to connect it to my nextcloud :/ 

But Chrome/Firefox doesn't seem to like it :/ 

do you know where i could find a solution please ? 

Thank you very much !! 

![image](https://github.com/afterlogic/nextcloud-connector/assets/34892879/8b287bb8-76ab-4605-8e9e-dd62d242bcc8)

**config**
```
nextcloud 28.0.3
afterlogic 2.0.9
```

**Comment by afterlogic-support** [comment]
By default, WebMail doesn't allow for integrating into IFrame due to security concerns. This is covered at https://afterlogic.com/docs/webmail-pro/configuring-webmail/nextcloud-integration page:

> ... if Nextcloud and WebMail Pro are in different domains, make sure you have XFrameOptions set to empty string in `data/settings/config.json` file, detailed information on this [is found here](https://afterlogic.com/docs/webmail-pro/security/preventing-clickjacking-attacks-with-x-frame-options-header).

**Comment by afterlogic-support** [comment]
Do you have WebMail and Nextcloud on different domains? Can you show how the domains look like - no need to specify actual domain, we just need a general idea. 

For example, Nextcloud is under my.domain.com/nextcloud while WebMail is under my.domain.com/afterlogic

**Comment by vianmora** [comment]
normally, no, it's configured like that : 
- afterlogic : `https://mail.my_domain.fr`
- nextcloud : `https://nextcloud.my_domain.fr/`

**Comment by afterlogic-support** [comment]
That looks like a caching issue to me, then. Be sure to clear web browser cache to apply changes. 

I've just tested this on my own installation of NextCloud accessed as next.domain.com, and WebMail installed under mail.domain.com, worked just fine upon setting `XFrameOptions` value to an empty string.

**Comment by vianmora** [comment]
nop :'( i've just cleaned the cache, and it's still blocked :/

**Comment by afterlogic-support** [comment]
I'm out of ideas then, I'm afraid. Make sure you're modifying the correct file, it should be `data/settings/config.json` file of your WebMail installation, and that you're replacing "SAMEORIGIN" with "" without adding any content to the file.

**Comment by vianmora** [comment]
hum... ok :'( 
well... i've tried to reinstall it yesterday, but it was the same, 
i don't really know where to go then :/ 
but thank you for your help ! 
I'll tried to find other solutions then for my compagny :)
