### ISSUE TITLE
add CardDAV connection to Nextcloud

### ISSUE THREAD

**Issue by nextgen-networks** [afterlogic/nextcloud-connector#5]
It would be fantastic to use the nextcloud contacts for afterlogic.
From user view a path/user/password to connect to that CardDAV driven informaton store would be the easiest way to implement that feature.

... maybe as one time paid extension/feature?

**Comment by afterlogic-support** [comment]
We consider adding other integration features for Nextcloud but that's not in roadmap yet. Custom development is an option of course, please contact us [via HelpDesk](https://s.afterlogic.com/helpdesk) if you may be interested.
