### ISSUE TITLE
No autologin

### ISSUE THREAD

**Issue by Peronia** [afterlogic/nextcloud-connector#6]
Hi,

at my nexcloud, the autologin doesnt work.
I fill out my details in my profile and the afterlogic is reachabel in nexcloud, but without autologin.

**Comment by afterlogic-support** [comment]
Check the webmail logs and see if login attempts are happening at all. Also, make sure you're able to log into the same account on that installation but without autologin.

**Comment by Peronia** [comment]
Well, thanks for the advice of the logs. Nevermind at that.
Seems to me that yout plugin isnt optimized fore shared hoster:

`file_exists(): open_basedir restriction in effect. File(/var/www/vhosts/hosting12671.a2fdc.netcup.net/httpdocs/afterlogic/system/Api.php) is not within the allowed path(s): (/var/www/vhosts/hosting12671.a2fdc.netcup.net/httpdocs/nextcloud/:/tmp/:/var/lib/php5/sessions:/var/www/vhosts/hosting12671.a2fdc.netcup.net/tmp) at /var/www/vhosts/hosting12671.a2fdc.netcup.net/httpdocs/nextcloud/apps/afterlogic/functions.php#31`
I fixed it by changing the open_basedir, but not so nice solution (I must grant the whole webroot the privilegdes).
