### ISSUE TITLE
Only works for admin users

### ISSUE THREAD

**Issue by Disco1** [afterlogic/nextcloud-connector#7]
Thanks for the Nextcloud plugin. Only problem is that it only shows up for admin users. Is this a configuration thing or a bug?

**Comment by afterlogic-support** [comment]
While setting up the plugin (Settings > Administration > Additional settings) is only available for admin users indeed, setting up email account access (Settings > Personal > Additional settings) should be available for any user. Are you saying that you have the plugin configured, with Path and URL specified for WebMail, but users don't have their settings screen to specify their email and password?

**Comment by Disco1** [comment]
Users don't see the icon in the top bar. Should they see something somewhere else?

Mon Sep 23 04:28:35 EDT 2019 AfterLogic Support <notifications@github.com>:

**Comment by afterlogic-support** [comment]
Yes, they should see Mail icon in the top bar - assuming the extension is configured, i.e. both URL and Path are specified in its configuration:
_
![nextcloud-mail](https://user-images.githubusercontent.com/16918936/65496546-548b9900-dec1-11e9-9858-dfc156e168dd.png)
_

**Comment by tombom105** [comment]
Hello,
I am currently also having this issue. The mail icon on the top bar only shows if a user is an admin for NextCloud. Is there a way to fix this?

**Comment by afterlogic-support** [comment]
Looks like the issue occurs only when "File path to AfterLogic WebMail installation" is not specified in app settings. It, however, is a valid approach for those cases when WebMail and NextCloud are on different servers, see [Nextcloud integration](https://afterlogic.com/docs/webmail-pro-8/configuring-webmail/nextcloud-integration) documentation page.

If that's the case, you can correct the issue by editing `apps/afterlogic/appinfo/app.php`, replace the following line:
```php
if (('' !== $sUrl && '' !== $sPath) || OC_User::isAdminUser(OC_User::getUser()))
```

with:

```php
if ('' !== $sUrl || OC_User::isAdminUser(OC_User::getUser()))
```

We'll have this modification added to the next update of the connector package.
