### ISSUE TITLE
Afterlogic webmail not startin

### ISSUE THREAD

**Issue by kadarpik** [afterlogic/nextcloud-connector#9]
icon is visible, but if I click into icon I get three header lines with application icons and all other area is blank.

file path:/var/www/nextcloud/apps/afterlogic
and web address is https://my_ip/apps/afterlogic

No errors in log file either. I might be related to rewrite rules  or something not allowing to access afterlogic php directory ?

**Comment by afterlogic-support** [comment]
> icon is visible, but if I click into icon I get three header lines with application icons and all other area is blank.

Can you post a screenshot reflecting that?

Also, it's not clear whether you have actually installed WebMail; this application is just a connector, you need to have Afterlogic WebMail installed separately on the same server.

**Comment by kadarpik** [comment]
Yes the screenshot is here


Toomas Kadarpik 
3kgroup OÜ
+372 55514009

**Comment by afterlogic-support** [comment]
We don't see the screenshot attached.

Also, this part remains unanswered:

> it's not clear whether you have actually installed WebMail; this application is just a connector, you need to have Afterlogic WebMail installed separately on the same server.

**Comment by kadarpik** [comment]
Checked there was attached file in sent items correctl. But here you see
the link
https://avalik.3kgroup.ee/index.php/s/NsRLqd5QNTASALe

*Toomas Kadarpik*



*Board member+372 55514009Skype: kadarpik*

*3KGroup OÜ*

*Ruckus Networks value added distributor*

*Pärnu mnt 139c kolmas korrus
<https://www.google.fi/maps/place/P%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti/@59.4063792,24.7341679,17z/data=!4m7!1m4!3m3!1s0x469294c3c45ab373:0xd01cdf63dfe36c23!2sP%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti!3b1!3m1!1s0x469294c3c45ab373:0xd01cdf63dfe36c23?hl=et>*
*Estonia*

**Comment by afterlogic-support** [comment]
OK, got it. But what about WebMail itself being installed explicitly, rather than just the connector?

**Comment by kadarpik** [comment]
I just want to use my imap/smtop server with nextcloud client like
rainloop, the latter works well but need some integration work to do.

*Toomas Kadarpik*



*Board member+372 55514009Skype: kadarpik*

*3KGroup OÜ*

*Ruckus Networks value added distributor*

*Pärnu mnt 139c kolmas korrus
<https://www.google.fi/maps/place/P%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti/@59.4063792,24.7341679,17z/data=!4m7!1m4!3m3!1s0x469294c3c45ab373:0xd01cdf63dfe36c23!2sP%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti!3b1!3m1!1s0x469294c3c45ab373:0xd01cdf63dfe36c23?hl=et>*
*Estonia*

**Comment by afterlogic-support** [comment]
Understood. Installing WebMail itself, however, is required for that. Installing just this connector isn't enough.

**Comment by kadarpik** [comment]
Any readme or guide for nextcloud installation  ?


*Toomas Kadarpik*



*Board member+372 55514009Skype: kadarpik*

*3KGroup OÜ*

*Ruckus Networks value added distributor*

*Pärnu mnt 139c kolmas korrus
<https://www.google.fi/maps/place/P%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti/@59.4063792,24.7341679,17z/data=!4m7!1m4!3m3!1s0x469294c3c45ab373:0xd01cdf63dfe36c23!2sP%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti!3b1!3m1!1s0x469294c3c45ab373:0xd01cdf63dfe36c23?hl=et>*
*Estonia*

**Comment by afterlogic-support** [comment]
Not really, standard installation instructions apply:
https://afterlogic.com/docs/webmail-pro-8/installation/installation-instructions

Once you have WebMail itself installed, you should be able to configure Nextcloud connector to work with it.

**Comment by kadarpik** [comment]
it is actually installed
 in my server

web url  https://files.3kgroup.ee/apps/afterlogic
flie path  /var/www/nextcloud/apps/afterlogic


*Toomas Kadarpik*



*Board member+372 55514009Skype: kadarpik*

*3KGroup OÜ*

*Ruckus Networks value added distributor*

*Pärnu mnt 139c kolmas korrus
<https://www.google.fi/maps/place/P%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti/@59.4063792,24.7341679,17z/data=!4m7!1m4!3m3!1s0x469294c3c45ab373:0xd01cdf63dfe36c23!2sP%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti!3b1!3m1!1s0x469294c3c45ab373:0xd01cdf63dfe36c23?hl=et>*
*Estonia*

**Comment by kadarpik** [comment]
is seems to be easier to write some code for rainloop probably that try to
integrate afterlogic to nextcloud, it seems to be not for NC
Or am I wrong ?


*Toomas Kadarpik*



*Board member+372 55514009Skype: kadarpik*

*3KGroup OÜ*

*Ruckus Networks value added distributor*

*Pärnu mnt 139c kolmas korrus
<https://www.google.fi/maps/place/P%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti/@59.4063792,24.7341679,17z/data=!4m7!1m4!3m3!1s0x469294c3c45ab373:0xd01cdf63dfe36c23!2sP%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti!3b1!3m1!1s0x469294c3c45ab373:0xd01cdf63dfe36c23?hl=et>*
*Estonia*

**Comment by afterlogic-support** [comment]
> web url  https://files.3kgroup.ee/apps/afterlogic
It won't open for us, but it doesn't look like a correct location of WebMail itself. I'd assume it's where the connector is.

> try to integrate afterlogic to nextcloud, it seems to be not for NC
This connector provides the minimal integration. We were asked to provide integration with files and contacts, but for now, it's just logging into the email account.

**Comment by kadarpik** [comment]
nothing opens from outside, it is all possible only via teamviewer with
observation ?
*Toomas Kadarpik*



*Board member+372 55514009Skype: kadarpik*

*3KGroup OÜ*

*Ruckus Networks value added distributor*

*Pärnu mnt 139c kolmas korrus
<https://www.google.fi/maps/place/P%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti/@59.4063792,24.7341679,17z/data=!4m7!1m4!3m3!1s0x469294c3c45ab373:0xd01cdf63dfe36c23!2sP%C3%A4rnu+maantee+139c,+11317+Tallinn,+Eesti!3b1!3m1!1s0x469294c3c45ab373:0xd01cdf63dfe36c23?hl=et>*
*Estonia*
